// <auto-generated />
using Inventory.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Inventory.Api.Migrations
{
    /// <summary>
    /// ثبت مایگریشن «مازادِ کارکرد». مدلِ هدف عمداً خالی گذاشته شده چون این مایگریشن
    /// فقط دستورهای SQL idempotent دارد (افزودن ستون) و مدلِ کامل در
    /// <c>AppDbContextModelSnapshot</c> نگه‌داری می‌شود.
    /// </summary>
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001120000_ExtraWorkDecision")]
    partial class ExtraWorkDecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
