// <auto-generated />
using System;
using Inventory.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Inventory.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001130000_ItRemoteRequestChannel")]
    partial class ItRemoteRequestChannel
    {
        /// <summary>
        /// مدلِ هدفِ مهاجرت کانال شرکت‌های راه‌دور؛ این فایل ادامهٔ کلاس migration است،
        /// نه تعریف دومِ AppDbContextModelSnapshot. snapshot اصلی در فایل خودش باقی می‌ماند.
        /// دستورهای SQL موجود در Up/Down تغییر نکرده‌اند.
        /// </summary>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            // ماژول درخواست خدمات آی‌تی و کانال شرکت‌های راه‌دور
            modelBuilder.Entity<ItRequest>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.Number).HasMaxLength(30);
                entity.Property(e => e.Title).HasMaxLength(200);
                entity.Property(e => e.Description).HasMaxLength(2000);
                entity.Property(e => e.RequestType).HasMaxLength(30);
                entity.Property(e => e.Status).HasMaxLength(30);
                entity.Property(e => e.SystemLabel).HasMaxLength(250);
                entity.Property(e => e.RequesterName).HasMaxLength(150);
                // ستون‌های تازهٔ کانال راه‌دور
                entity.Property(e => e.ExternalRequesterKey).HasMaxLength(40);
                entity.Property(e => e.ExternalId).HasMaxLength(40);
                entity.Property(e => e.RequesterPhone).HasMaxLength(30);
                entity.Property(e => e.RequesterEmail).HasMaxLength(120);
                entity.Property(e => e.TrackToken).HasMaxLength(40);
                entity.ToTable("ItRequests");
            });

            modelBuilder.Entity<ItRequestAttachment>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.FileName).HasMaxLength(255);
                entity.ToTable("ItRequestAttachments");
            });

            modelBuilder.Entity<ItRequestLog>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.Action).HasMaxLength(200);
                entity.Property(e => e.ActorName).HasMaxLength(150);
                entity.ToTable("ItRequestLogs");
            });

            modelBuilder.Entity<ItRequestSeen>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.ToTable("ItRequestSeens");
            });

            // ---------------- کانال شرکت‌های راه‌دور ----------------

            modelBuilder.Entity<ItClientCompany>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.Code).HasMaxLength(50).IsRequired();
                entity.Property(e => e.Name).HasMaxLength(200).IsRequired();
                entity.Property(e => e.Phone).HasMaxLength(50);
                entity.Property(e => e.ApiKeyHash).HasMaxLength(100).IsRequired();
                entity.Property(e => e.ApiKeyHint).HasMaxLength(10);
                entity.Property(e => e.Note).HasMaxLength(500);
                entity.HasIndex(e => e.Code).IsUnique();
                entity.ToTable("ItClientCompanies");
            });

            modelBuilder.Entity<ItRemoteConnection>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();
                entity.Property(e => e.ServerUrl).HasMaxLength(300);
                entity.Property(e => e.CompanyCode).HasMaxLength(50);
                entity.Property(e => e.CompanyName).HasMaxLength(200);
                entity.Property(e => e.ApiKey).HasMaxLength(100);
                entity.ToTable("ItRemoteConnections");
            });

            modelBuilder.Entity<ItRemoteRequest>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.RemoteNumber).HasMaxLength(30);
                entity.Property(e => e.TrackToken).HasMaxLength(40);
                entity.Property(e => e.ExternalId).HasMaxLength(40).IsRequired();
                entity.Property(e => e.RequesterKey).HasMaxLength(40).IsRequired();
                entity.Property(e => e.RequesterName).HasMaxLength(150).IsRequired();
                entity.Property(e => e.SystemLabel).HasMaxLength(250);
                entity.Property(e => e.RequestType).HasMaxLength(30).IsRequired();
                entity.Property(e => e.Title).HasMaxLength(200).IsRequired();
                entity.Property(e => e.Description).HasMaxLength(2000).IsRequired();
                entity.Property(e => e.Status).HasMaxLength(30).IsRequired();
                entity.Property(e => e.FinalResponse).HasMaxLength(4000);
                entity.Property(e => e.LastError).HasMaxLength(500);
                entity.HasIndex(e => e.LocalUserId);
                entity.HasIndex(e => e.RemoteNumber);
                entity.ToTable("ItRemoteRequests");
            });

            modelBuilder.Entity<ItRemoteUserKey>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.Key).HasMaxLength(40).IsRequired();
                entity.HasIndex(e => e.UserId).IsUnique();
                entity.ToTable("ItRemoteUserKeys");
            });
        }
    }
}
